import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT=process.cwd(), RAW=path.join(ROOT,'public','data','raw'), OUT=path.join(ROOT,'src','data','realData.json');
const BASE=process.env.OLIST_BASE_URL||'https://raw.githubusercontent.com/Sangamesh2703/Brazilian-E-Commerce/main';
const ALLOW_DOWNLOAD=process.env.OLIST_ALLOW_DOWNLOAD==='1';
const files=['olist_orders_dataset.csv','olist_order_items_dataset.csv','olist_order_payments_dataset.csv','olist_order_reviews_dataset.csv','olist_customers_dataset.csv','olist_sellers_dataset.csv','olist_products_dataset.csv','product_category_name_translation.csv'];
const aliases={};
for(const f of files) aliases[f]=[f.replace('olist_','')];
await fs.mkdir(RAW,{recursive:true}); await fs.mkdir(path.dirname(OUT),{recursive:true});
async function findLocal(file){const names=[file,...(aliases[file]||[])];const dirs=[RAW,path.join(ROOT,'data','olist'),path.join(ROOT,'public','data','olist'),path.join(ROOT,'public','data'),path.join(ROOT,'data','raw'),path.join(ROOT,'data'),ROOT];for(const d of dirs)for(const n of names){const p=path.join(d,n);try{const s=await fs.stat(p);if(s.size>100)return p}catch{}}return null}
async function getFile(file){const local=await findLocal(file);if(local)return local;if(!ALLOW_DOWNLOAD)throw new Error(`Missing local dataset file: ${file}`);const dest=path.join(RAW,file);let last;for(let i=0;i<3;i++){try{const r=await fetch(`${BASE}/${encodeURIComponent(file)}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());if(b.length<100)throw new Error('Downloaded file is unexpectedly small');await fs.writeFile(dest,b);return dest}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,600*(i+1)))}}throw new Error(`Could not download ${file}: ${last?.message||last}`)}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++}else quoted=false}else field+=c}else{if(c==='"'&&field==='')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}}if(field.length||row.length){row.push(field);rows.push(row)}const headers=(rows.shift()||[]).map(h=>h.trim());return rows.filter(r=>r.some(v=>v!=='' )).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
const raw={};for(const f of files){try{const p=await getFile(f);raw[f]=await fs.readFile(p,'utf8')}catch(e){
  try{
    const existing=JSON.parse(await fs.readFile(OUT,'utf8'));
    if(existing&&existing.ready){
      console.log(`Parakh prebuild: keeping existing pre-built dataset (${existing.merchants?.length||0} sellers).`);
      process.exit(0);
    }
  }catch{}
  const out={ready:false,error:e.message,source:'Olist Brazilian E-Commerce Public Dataset',sourceUrl:'https://www.kaggle.com/olistbr/brazilian-ecommerce'};await fs.writeFile(OUT,JSON.stringify(out,null,2));console.error(`\nParakh data bootstrap failed: ${e.message}\n`);process.exit(0)}}
const orders=parseCsv(raw[files[0]]),items=parseCsv(raw[files[1]]),payments=parseCsv(raw[files[2]]),reviews=parseCsv(raw[files[3]]),customers=parseCsv(raw[files[4]]),sellers=parseCsv(raw[files[5]]),productsRaw=parseCsv(raw[files[6]]),translations=parseCsv(raw[files[7]]);
const orderMap=new Map(orders.map(x=>[x.order_id,x])),sellerMap=new Map(sellers.map(x=>[x.seller_id,x])),customerMap=new Map(customers.map(x=>[x.customer_id,x])),productMap=new Map(productsRaw.map(x=>[x.product_id,x])),transMap=new Map(translations.map(x=>[x.product_category_name,x.product_category_name_english]));
const paymentByOrder=new Map();for(const p of payments){const v=Number(p.payment_value)||0;paymentByOrder.set(p.order_id,(paymentByOrder.get(p.order_id)||0)+v)}
const reviewByOrder=new Map();for(const r of reviews){if(!reviewByOrder.has(r.order_id))reviewByOrder.set(r.order_id,[]);const n=Number(r.review_score);if(Number.isFinite(n))reviewByOrder.get(r.order_id).push(n)}
const agg=new Map(), monthAgg=new Map(), sellerCustomerCounts=new Map(), customerSellerSets=new Map(), productAgg=new Map();
for(const it of items){const o=orderMap.get(it.order_id),s=sellerMap.get(it.seller_id);if(!o||!s)continue;const price=Number(it.price)||0,freight=Number(it.freight_value)||0,c=customerMap.get(o.customer_id),cid=c?.customer_unique_id||o.customer_id;
 let m=agg.get(it.seller_id);if(!m){m={sellerId:it.seller_id,city:s.seller_city,state:s.seller_state,orders:new Set(),items:0,revenue:0,freight:0,delivered:0,cancelled:0,late:0,reviewTotal:0,reviewCount:0,customers:new Set(),categories:new Map(),cIds:[],lIds:[],rIds:[]};agg.set(it.seller_id,m)}
 m.orders.add(it.order_id);m.items++;m.revenue+=price;m.freight+=freight;if(cid)m.customers.add(cid);if(o.order_status==='delivered')m.delivered++;if(o.order_status==='canceled'){m.cancelled++;if(m.cIds.length<50&&!m.cIds.includes(it.order_id))m.cIds.push(it.order_id)}const revs=reviewByOrder.get(it.order_id)||[];if(revs.length){m.reviewTotal+=revs[0];m.reviewCount++;if(revs[0]<=2&&m.rIds.length<50&&!m.rIds.includes(it.order_id))m.rIds.push(it.order_id)}const d=o.order_delivered_customer_date?new Date(o.order_delivered_customer_date):null,e=o.order_estimated_delivery_date?new Date(o.order_estimated_delivery_date):null;if(d&&e&&d>e){m.late++;if(m.lIds.length<50&&!m.lIds.includes(it.order_id))m.lIds.push(it.order_id)}const dt=new Date(o.order_purchase_timestamp);if(!Number.isNaN(dt.valueOf())){const month=dt.toISOString().slice(0,7);monthAgg.set(`${it.seller_id}|${month}`,(monthAgg.get(`${it.seller_id}|${month}`)||0)+price)}
 if(!sellerCustomerCounts.has(it.seller_id))sellerCustomerCounts.set(it.seller_id,new Map());const scm=sellerCustomerCounts.get(it.seller_id);scm.set(cid,(scm.get(cid)||0)+1);if(!customerSellerSets.has(cid))customerSellerSets.set(cid,new Set());customerSellerSets.get(cid).add(it.seller_id);
 const prod=productMap.get(it.product_id);const cat=transMap.get(prod?.product_category_name)||prod?.product_category_name||'unknown';m.categories.set(cat,(m.categories.get(cat)||0)+price);let pa=productAgg.get(it.product_id);if(!pa){pa={id:it.product_id,category:cat,orders:new Set(),items:0,revenue:0,prices:[],sellers:new Set()};productAgg.set(it.product_id,pa)}pa.orders.add(it.order_id);pa.items++;pa.revenue+=price;pa.prices.push(price);pa.sellers.add(it.seller_id)
}
const dates=orders.map(o=>new Date(o.order_purchase_timestamp)).filter(d=>!Number.isNaN(d.valueOf())),minDate=dates.reduce((a,b)=>a<b?a:b),maxDate=dates.reduce((a,b)=>a>b?a:b);const months=[...new Set(dates.map(d=>d.toISOString().slice(0,7)))].sort();
function pct(values,v){const a=[...values].sort((x,y)=>x-y);if(!a.length)return 0;let lo=0,hi=a.length;while(lo<hi){const mid=(lo+hi)>>1;if(a[mid]<=v)lo=mid+1;else hi=mid}return Math.round((lo/a.length)*100)}
const base=[...agg.values()].map(m=>{const oc=m.orders.size,cr=m.cancelled/Math.max(1,oc),lr=m.late/Math.max(1,m.delivered),rv=m.reviewTotal/Math.max(1,m.reviewCount),repeat=m.customers.size/Math.max(1,oc),scm=sellerCustomerCounts.get(m.sellerId)||new Map(),top=Math.max(0,...scm.values())/Math.max(1,oc),shared=[...scm.keys()].filter(cid=>(customerSellerSets.get(cid)?.size||0)>1).length,overlap=shared/Math.max(1,m.customers.size);return {...m,oc,cr,lr,rv,repeat,top,shared,overlap}});
const crs=base.map(x=>x.cr),lrs=base.map(x=>x.lr),tops=base.map(x=>x.top),ovls=base.map(x=>x.overlap),lowReviews=base.map(x=>5-x.rv);
const merchants=base.map(m=>{const anomaly=Math.round((pct(crs,m.cr)+pct(lrs,m.lr)+pct(tops,m.top)+pct(ovls,m.overlap)+pct(lowReviews,5-m.rv))/5);const score=Math.max(20,Math.min(98,Math.round(100-(pct(crs,m.cr)*.25+pct(lrs,m.lr)*.25+pct(lowReviews,5-m.rv)*.15+pct(tops,m.top)*.2+pct(ovls,m.overlap)*.15))));const carat=`${Math.max(12,Math.min(24,Math.round(score/4.15)))}K`;const monthly=months.slice(-6).map(month=>({month,revenue:monthAgg.get(`${m.sellerId}|${month}`)||0}));const first=monthly[0]?.revenue||0,last=monthly.at(-1)?.revenue||0,trend=first?((last-first)/first)*100:0;const cats=[...m.categories.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,revenue])=>({name,revenue}));const reasons=[['Cancellation concentration',pct(crs,m.cr)],['Late-delivery concentration',pct(lrs,m.lr)],['Single-customer concentration',pct(tops,m.top)],['Shared-customer network concentration',pct(ovls,m.overlap)],['Low-review concentration',pct(lowReviews,5-m.rv)]].filter(([,v])=>v>=70).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([label,v])=>`${label}: ${v}th percentile`);return {id:m.sellerId,name:`Seller ${m.sellerId.slice(0,8)}`,city:m.city,state:m.state,orders:m.oc,items:m.items,revenue:Number(m.revenue.toFixed(2)),freight:Number(m.freight.toFixed(2)),customers:m.customers.size,reviewAvg:Number(m.rv.toFixed(2)),cancelRate:Number((m.cr*100).toFixed(2)),lateRate:Number((m.lr*100).toFixed(2)),repeatRate:Number((m.repeat*100).toFixed(2)),topCustomerShare:Number((m.top*100).toFixed(2)),sharedCustomerRate:Number((m.overlap*100).toFixed(2)),sharedCustomerCount:m.shared,networkAnomaly:anomaly,score,carat,trend:Number(trend.toFixed(2)),categories:cats,monthly,evidence:{cancelled:m.cIds,late:m.lIds,lowReview:m.rIds},factors:reasons.map((x)=>({key:x,label:x,points:0,value:'Observed in source-data distribution'}))}}).sort((a,b)=>b.revenue-a.revenue);
const fraudSignals=merchants.map(m=>({id:m.id,anomalyScore:m.networkAnomaly,reasons:m.factors.map(f=>f.label),sharedCustomerRate:m.sharedCustomerRate,topCustomerShare:m.topCustomerShare})).sort((a,b)=>b.anomalyScore-a.anomalyScore);
const products=[...productAgg.values()].map(p=>{const meta=productMap.get(p.id)||{};return {id:p.id,name:meta.product_name||p.id,category:p.category,orders:p.orders.size,items:p.items,revenue:Number(p.revenue.toFixed(2)),avgPrice:Number((p.prices.reduce((a,b)=>a+b,0)/Math.max(1,p.prices.length)).toFixed(2)),sellers:p.sellers.size,weightG:Number(meta.product_weight_g)||0,categoryLength:Number(meta.product_name_lenght)||0,descriptionLength:Number(meta.product_description_lenght)||0}}).sort((a,b)=>b.revenue-a.revenue);
const edges=[];const edgeSeen=new Set();const relevantSellers=new Set(fraudSignals.slice(0,Math.min(fraudSignals.length,80)).map(x=>x.id));for(const it of items){if(!relevantSellers.has(it.seller_id))continue;const o=orderMap.get(it.order_id),c=customerMap.get(o?.customer_id),cid=c?.customer_unique_id||o?.customer_id;if(!cid)continue;const key=`${it.seller_id}|${cid}`;if(edgeSeen.has(key))continue;edgeSeen.add(key);edges.push({seller:it.seller_id,customer:cid,orderId:it.order_id})}
const duplicateOrderIds=orders.length-new Set(orders.map(x=>x.order_id)).size;const rejectedRows=orders.filter(x=>!x.order_id||!x.customer_id||!x.order_status).slice(0,50);const fieldCatalog=[...new Set([...orders,...items,...payments,...customers,...sellers,...productsRaw].flatMap(r=>Object.keys(r)))].map(name=>({name,type:/price|value|freight|weight|length|height|width|payment_installments|review_score/.test(name)?'number':/date|timestamp/.test(name)?'date':'text'}));
const out={ready:true,source:'Olist Brazilian E-Commerce Public Dataset',sourceUrl:'https://www.kaggle.com/olistbr/brazilian-ecommerce',summary:{orders:orders.length,sellers:sellers.length,customers:customers.length,items:items.length,payments:payments.length,reviews:reviews.length,products:productsRaw.length,from:minDate.toISOString(),to:maxDate.toISOString(),months},merchants,products,fraudSignals,edges,fieldCatalog,quality:{duplicates:duplicateOrderIds,rejected:rejectedRows.length,kept:Math.max(0,orders.length-duplicateOrderIds-rejectedRows.length),keptPercent:(Math.max(0,orders.length-duplicateOrderIds-rejectedRows.length)/Math.max(1,orders.length)*100).toFixed(2),rejectedRows},generatedAt:new Date().toISOString(),notes:['Real commercial Olist data, anonymised.','FraudSignals are data-driven anomaly indicators, not confirmed fraud labels.','Risk scores use relative dataset distributions rather than fixed business thresholds.']};
await fs.writeFile(OUT,JSON.stringify(out));console.log(`Parakh: processed ${merchants.length} sellers, ${products.length} products and ${orders.length} real Olist orders.`)
