import {useMemo,useState} from 'react';
import {ArrowRight,Database,AlertTriangle,Store,ExternalLink,SlidersHorizontal,PackageSearch} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {useApp} from '../context/AppContext';
import {getProducts} from '../data/realData';
export default function Home(){
 const nav=useNavigate();const {role,userName,dataset,merchants}=useApp();const [prompt,setPrompt]=useState('');const [controls,setControls]=useState({state:'All',category:'All',minValue:'',maxValue:''});const s=dataset?.summary||{};const products=getProducts();
 const states=useMemo(()=>['All',...new Set(merchants.map(x=>x.state).filter(Boolean))].sort(),[merchants]);
 const categories=useMemo(()=>['All',...new Set(products.map(x=>x.category).filter(Boolean))].sort(),[products]);
 const submit=e=>{e.preventDefault();if(prompt.trim()||Object.values(controls).some(v=>v&&v!=='All'))nav('/workflows',{state:{prompt:prompt||'Analyse the selected records',controls}})};
 if(!dataset?.ready)return <div className="panel p-8 max-w-3xl"><div className="eyebrow">Real data setup</div><h1 className="serif text-5xl mt-2">Olist data is not loaded yet.</h1><p className="text-muted mt-4 leading-7">Place the real CSV files in <span className="mono text-gold">public/data/raw</span> and run <span className="mono text-gold">npm run prepare:data</span>.</p><a className="text-gold underline mt-5 inline-flex items-center gap-2" href="https://www.kaggle.com/olistbr/brazilian-ecommerce" target="_blank" rel="noreferrer">Dataset source <ExternalLink size={14}/></a></div>;
 return <div><div className="flex justify-between items-end mb-10"><div><div className="eyebrow">Home / {role}</div><h1 className="serif text-5xl mt-2">Welcome, {userName||role}.</h1><p className="text-muted mt-2">Ask anything about the loaded records. Filters are optional.</p></div></div>
 <form onSubmit={submit} className="panel p-6 mb-4 max-w-6xl"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Tell us what to look at: seller, product, revenue, delivery, anomaly, category..." className="w-full min-h-[150px] bg-transparent resize-none outline-none text-2xl serif placeholder:text-muted/60"/><div className="flex justify-end"><button className="btn-gold px-5 py-2 flex gap-2 items-center">Build workflow <ArrowRight size={16}/></button></div></form>
 <div className="panel p-5 max-w-6xl mb-10"><div className="flex items-center gap-2 eyebrow"><SlidersHorizontal size={13}/> Optional data filters</div><div className="grid md:grid-cols-4 gap-3 mt-4"><label className="text-xs text-muted">State<select value={controls.state} onChange={e=>setControls(c=>({...c,state:e.target.value}))} className="input-dark w-full p-2 mt-1"><option>All</option>{states.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-muted">Product category<select value={controls.category} onChange={e=>setControls(c=>({...c,category:e.target.value}))} className="input-dark w-full p-2 mt-1"><option>All</option>{categories.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-muted">Minimum revenue/value<input value={controls.minValue} onChange={e=>setControls(c=>({...c,minValue:e.target.value}))} type="number" min="0" placeholder="e.g. 10000" className="input-dark w-full p-2 mt-1"/></label><label className="text-xs text-muted">Maximum revenue/value<input value={controls.maxValue} onChange={e=>setControls(c=>({...c,maxValue:e.target.value}))} type="number" min="0" placeholder="e.g. 50000" className="input-dark w-full p-2 mt-1"/></label></div><p className="text-[11px] text-muted mt-3">Nothing here is a hardcoded business value. Filters are read from your input and calculations come from the loaded CSV records.</p></div>
 <div className="mb-12 max-w-6xl"><div className="eyebrow mb-3">Try these</div><div className="flex flex-wrap gap-x-7 gap-y-2"><button onClick={()=>setPrompt('Find sellers with unusual customer concentration')} className="text-sm underline underline-offset-4">Unusual customer concentration</button><button onClick={()=>setPrompt('Compare product categories by revenue and average price')} className="text-sm underline underline-offset-4">Product category revenue</button><button onClick={()=>setPrompt('Find sellers with high cancellation and late delivery rates')} className="text-sm underline underline-offset-4">Operational risk</button></div></div>
 <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><div className="panel p-6"><div className="eyebrow">Loaded dataset</div><div className="grid grid-cols-3 mt-5 divide-x divide-white/10"><div className="pr-5"><Store size={18} className="text-gold mb-3"/><div className="mono text-3xl">{s.sellers?.toLocaleString('en-IN')}</div><p className="text-xs text-muted mt-1">real sellers</p></div><div className="px-5"><Database size={18} className="text-steel mb-3"/><div className="mono text-3xl">{s.orders?.toLocaleString('en-IN')}</div><p className="text-xs text-muted mt-1">real orders</p></div><div className="pl-5"><PackageSearch size={18} className="text-fraud mb-3"/><div className="mono text-3xl">{s.products?.toLocaleString('en-IN')}</div><p className="text-xs text-muted mt-1">real products</p></div></div><p className="text-[11px] text-muted mt-6">Coverage: {new Date(s.from).toLocaleDateString()} → {new Date(s.to).toLocaleDateString()}</p></div><div className="panel p-6"><div className="eyebrow">How Parakh works</div><p className="serif text-2xl mt-3">Question → data selection → calculation → evidence.</p><p className="text-sm text-muted mt-2">Metrics, product values and anomaly signals are calculated from the CSV fields. No seeded merchant values are used.</p></div></div></div>
}
