import {useMemo,useState} from 'react';
import {Info,Search} from 'lucide-react';
import {getIndiaData} from '../data/indiaData';
const CR=1e7, LCR=1e12;
const inr=v=>v>=LCR?`Rs ${(v/LCR).toLocaleString('en-IN',{maximumFractionDigits:2})} lakh cr`:v>=CR?`Rs ${(v/CR).toLocaleString('en-IN',{maximumFractionDigits:0})} cr`:`Rs ${Math.round(v).toLocaleString('en-IN')}`;
const cnt=v=>v>=CR?`${(v/CR).toLocaleString('en-IN',{maximumFractionDigits:v>=CR*100?0:2})} cr`:Math.round(v).toLocaleString('en-IN');
const pct=v=>v==null?'—':`${v>=0?'+':''}${v.toLocaleString('en-IN',{maximumFractionDigits:1})}%`;
export default function India(){
 const d=getIndiaData();const [q,setQ]=useState('');const [all,setAll]=useState(false);
 const states=useMemo(()=>{const s=q.toLowerCase().trim();const rows=(d.states||[]).filter(x=>!s||`${x.state} ${x.region}`.toLowerCase().includes(s));return all||s?rows:rows.slice(0,12)},[d,q,all]);
 if(!d.ready)return <div className="panel p-8 max-w-3xl"><div className="eyebrow">India market context</div><h1 className="serif text-5xl mt-2">India data is not prepared yet.</h1><p className="text-muted mt-4 leading-7">Run <span className="mono text-gold">python scripts/prepare-india-data.py</span> to build it from <span className="mono text-gold">public/data/india/district_transactions.parquet</span>.</p></div>;
 const sm=d.summary,nat=d.national,last=nat[nat.length-1],recent=nat.slice(-12),max=Math.max(...recent.map(x=>x.amount));
 const yr=nat.filter(x=>x.quarter.startsWith(`${sm.latestYear}-`)),pyr=nat.filter(x=>x.quarter.startsWith(`${sm.latestYear-1}-`));
 const yAmt=yr.reduce((a,b)=>a+b.amount,0),yCnt=yr.reduce((a,b)=>a+b.count,0),pAmt=pyr.reduce((a,b)=>a+b.amount,0);
 const growth=pAmt?((yAmt-pAmt)/pAmt)*100:null;
 return <div><div className="eyebrow">India market context</div><h1 className="serif text-5xl mt-2">India Payments</h1><p className="text-muted mt-2 max-w-3xl">District-level UPI transaction aggregates, {sm.firstQuarter} to {sm.lastQuarter}. Used as market context next to the Olist merchant analysis.</p>
 <div className="panel p-4 mt-6 max-w-5xl flex gap-3 text-sm"><Info size={16} className="text-gold shrink-0 mt-0.5"/><p className="text-muted leading-6">This is <span className="text-bone">aggregate</span> state / district / quarter data. It is not merchant-level, carries no fraud labels, and is not joined to the Olist (Brazil) sellers. Olist values are in Brazilian Real and are not compared against these rupee figures.</p></div>
 <div className="grid md:grid-cols-4 gap-4 mt-5">{[[`Transactions ${sm.latestYear}`,cnt(yCnt)],[`Value ${sm.latestYear}`,inr(yAmt)],['Avg ticket (latest qtr)',`Rs ${last.avgTicket.toLocaleString('en-IN',{maximumFractionDigits:0})}`],[`Value growth vs ${sm.latestYear-1}`,pct(growth)]].map(([k,v])=><div key={k} className="panel p-5"><div className="eyebrow">{k}</div><div className="mono text-2xl mt-3">{v}</div></div>)}</div>
 <div className="panel p-6 mt-5"><div className="eyebrow">Transaction value by quarter · last 12 quarters</div><div className="flex items-end gap-2 mt-5 h-44">{recent.map(x=><div key={x.quarter} className="flex-1 flex flex-col items-center justify-end h-full" title={`${x.quarter}: ${inr(x.amount)}`}><div className="w-full bg-gold/70" style={{height:`${Math.max(3,x.amount/max*100)}%`}}/><div className="mono text-[9px] text-muted mt-2">{x.quarter.slice(2)}</div></div>)}</div></div>
 <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-5 mt-5"><div className="panel overflow-auto"><div className="eyebrow p-4 pb-2">Regions · {sm.latestYear}</div><table className="w-full text-sm"><thead className="text-muted text-xs"><tr className="border-b border-white/10">{['Region','Value','Share'].map(x=><th key={x} className="text-left p-3 font-normal">{x}</th>)}</tr></thead><tbody>{d.regions.map(r=><tr key={r.region} className="border-b border-white/5"><td className="p-3">{r.region}</td><td className="mono">{inr(r.amount)}</td><td className="mono">{r.shareOfNationalPct}%</td></tr>)}</tbody></table></div>
 <div className="panel overflow-auto"><div className="eyebrow p-4 pb-2">Top districts · {sm.latestYear}</div><table className="w-full text-sm"><thead className="text-muted text-xs"><tr className="border-b border-white/10">{['District','State','Value','Avg ticket'].map(x=><th key={x} className="text-left p-3 font-normal">{x}</th>)}</tr></thead><tbody>{d.topDistricts.slice(0,10).map(r=><tr key={r.state+r.district} className="border-b border-white/5"><td className="p-3">{r.district}</td><td className="text-muted">{r.state}</td><td className="mono">{inr(r.amount)}</td><td className="mono">Rs {r.avgTicket.toLocaleString('en-IN',{maximumFractionDigits:0})}</td></tr>)}</tbody></table></div></div>
 <div className="panel mt-5 overflow-auto"><div className="p-4 flex gap-3 flex-wrap items-center"><div className="eyebrow">States · {sm.latestYear}</div><div className="relative flex-1 min-w-64"><Search size={15} className="absolute left-3 top-3 text-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search state or region" className="input-dark w-full p-2.5 pl-9"/></div></div><table className="w-full text-sm"><thead className="text-muted text-xs"><tr className="border-b border-white/10">{['State','Region','Transactions','Value','Avg ticket','Growth','Share'].map(x=><th key={x} className="text-left p-3 font-normal">{x}</th>)}</tr></thead><tbody>{states.map(s=><tr key={s.state} className="border-b border-white/5 hover:bg-white/[.02]"><td className="p-3">{s.state}</td><td className="text-muted">{s.region}</td><td className="mono">{cnt(s.count)}</td><td className="mono">{inr(s.amount)}</td><td className="mono">Rs {s.avgTicket.toLocaleString('en-IN',{maximumFractionDigits:0})}</td><td className="mono">{pct(s.yoyGrowthPct)}</td><td className="mono">{s.shareOfNationalPct}%</td></tr>)}{!states.length&&<tr><td colSpan={7} className="p-4 text-xs text-muted">No state matches.</td></tr>}</tbody></table>{!q&&!all&&<div className="p-3"><button onClick={()=>setAll(true)} className="btn-quiet px-3 py-1 text-xs">Show all {d.states.length} states</button></div>}</div>
 </div>
}
