import {useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Search} from 'lucide-react';
import {merchantResults} from '../data/realData';
import {useApp} from '../context/AppContext';
export default function Merchants(){
 const nav=useNavigate(),{setSelectedMerchantId}=useApp();const all=useMemo(()=>merchantResults(),[]);const[q,setQ]=useState('');const[state,setState]=useState('All');const[page,setPage]=useState(1);const size=20;const states=['All',...new Set(all.map(x=>x.state))];
 const filtered=all.filter(m=>(!q||`${m.id} ${m.city} ${m.state}`.toLowerCase().includes(q.toLowerCase()))&&(state==='All'||m.state===state));const rows=filtered.slice((page-1)*size,page*size);return <div><div className="eyebrow">Real seller book</div><h1 className="serif text-5xl mt-2">Merchants</h1><div className="panel mt-6 p-4 flex gap-3 flex-wrap"><div className="relative flex-1 min-w-64"><Search size={15} className="absolute left-3 top-3 text-muted"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search seller ID, city or state" className="input-dark w-full p-2.5 pl-9"/></div><select value={state} onChange={e=>{setState(e.target.value);setPage(1)}} className="input-dark p-2.5">{states.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="panel mt-4 overflow-hidden"><table className="w-full text-sm"><thead className="text-muted text-xs"><tr className="border-b border-white/10">{['Seller','City','State','Orders','Revenue','Carat','Score'].map(x=><th className="text-left p-3 font-normal" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(m=><tr key={m.id} className="border-b border-white/5 hover:bg-white/[.02] cursor-pointer" onClick={()=>{setSelectedMerchantId(m.id);nav(`/merchants/${m.id}`)}}><td className="p-3">{m.id}</td><td>{m.city}</td><td>{m.state}</td><td className="mono">{m.orders.toLocaleString('en-IN')}</td><td className="mono">R$ {m.revenue.toLocaleString('en-IN',{maximumFractionDigits:0})}</td><td className="mono text-gold">{m.carat}</td><td className="mono">{m.score}/100</td></tr>)}</tbody></table></div><div className="flex justify-between items-center mt-4 mono text-xs text-muted"><span>{filtered.length.toLocaleString('en-IN')} sellers</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(page-1)} className="btn-quiet px-3 py-1">Prev</button><span className="p-2">Page {page}/{Math.max(1,Math.ceil(filtered.length/size))}</span><button disabled={page>=Math.ceil(filtered.length/size)} onClick={()=>setPage(page+1)} className="btn-quiet px-3 py-1">Next</button></div></div></div>
}
