import {useEffect,useMemo,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Check,Download,Volume2,ShieldCheck,ShieldAlert} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {getFraudSignals,networkData} from '../data/realData';
import {explain,stress,actions,leak,fairness,clusters,proof,sha,speech,ask,carat,R} from '../lib/trust';
const TABS=[['dq','Data quality'],['sc','Seller score'],['nw','Network'],['fa','Fairness'],['st','Stress & actions'],['pf','Proof'],['as','Assistant']];
const dl=(n,t,ty)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:ty}));a.download=n;a.click()};
const Th=({c})=><tr className="border-b border-white/10 text-muted text-xs">{c.map(x=><th key={x} className="text-left p-3 font-normal">{x}</th>)}</tr>;
const Stat=({l,v,bad})=><div className="panel p-5"><div className="eyebrow">{l}</div><div className={`serif text-4xl mt-2 ${bad?'text-fraud':''}`}>{v}</div></div>;
export default function TrustLab(){
 const {merchants:all,dataset:ds,selectedMerchantId,setSelectedMerchantId}=useApp();const edges=useMemo(()=>networkData(),[]);
 const [tab,setTab]=useState('dq'),[q,setQ]=useState(''),[st,setSt]=useState('All'),[ev,setEv]=useState(null),[sl,setSl]=useState({demand:0,downtime:0,sales:0}),[pf,setPf]=useState(null),[vr,setVr]=useState(''),[vh,setVh]=useState(''),[chat,setChat]=useState([]),[ci,setCi]=useState('');
 const m=all.find(x=>x.id===selectedMerchantId)||all[0];
 const r=useMemo(()=>m&&explain(m,all,edges),[m,all,edges]);
 const fa=useMemo(()=>tab==='fa'?fairness(all):null,[tab,all]);
 useEffect(()=>{if(m&&r)proof(m,r,ds).then(p=>{setPf(p);setVh(p.hash);setVr('')})},[m,r,ds]);
 if(!ds?.ready||!m)return <div className="panel p-7">Load the real Olist dataset first.</div>;
 const states=['All',...new Set(all.map(x=>x.state))].sort();
 const list=all.filter(x=>(st==='All'||x.state===st)&&(!q||`${x.id} ${x.city} ${x.state}`.toLowerCase().includes(q.toLowerCase())));
 const say=t=>{try{const u=new SpeechSynthesisUtterance(t);const voices=window.speechSynthesis?.getVoices?.()||[];const preferred=voices.find(v=>/hi[-_]?IN/i.test(v.lang)&&/(google hindi|swara|kalpana|heera|aditi)/i.test(v.name))||voices.find(v=>/^hi/i.test(v.lang))||voices.find(v=>/hi[-_]?IN/i.test(v.lang))||voices.find(v=>/[-_]IN/i.test(v.lang));if(preferred)u.voice=preferred;u.lang='hi-IN';u.rate=0.90;u.pitch=1.05;speechSynthesis.cancel();speechSynthesis.speak(u)}catch{}};
 const sr=stress(m,all,sl),lk=leak(m),ac=actions(m,all).filter(a=>a.delta>0),cl=useMemo(()=>clusters(edges),[edges]);
 const submit=()=>{if(!ci.trim())return;setChat(c=>[...c,['You',ci],['Parakh',ask(ci,{m,r,all,edges,ds})]]);setCi('')};
 const rej=(ds.quality?.rejectedRows||[]).map(x=>({id:x.order_id||'(missing order_id)',why:['order_id','customer_id','order_status'].filter(k=>!x[k]).map(k=>`missing ${k}`).join(', ')||'failed validation'}));
 return <div className="max-w-6xl"><div className="eyebrow">Trust · fraud · fairness</div><h1 className="serif text-5xl mt-2">Trust Lab</h1>
 <p className="text-muted mt-2 max-w-3xl">Every figure on this page is calculated from the loaded Olist records. Amounts are in Brazilian Real (R$). Nothing is seeded, simulated or typed in.</p>
 <div className="panel mt-6 p-4 flex flex-wrap gap-3">{TABS.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2 ${tab===k?'btn-gold':'btn-quiet'}`}>{l}</button>)}</div>
 {tab==='dq'&&<div className="mt-5"><div className="grid md:grid-cols-4 gap-4"><Stat l="Orders received" v={ds.summary.orders.toLocaleString('en-IN')}/><Stat l="Duplicates removed" v={ds.quality.duplicates}/><Stat l="Rows rejected" v={ds.quality.rejected} bad={ds.quality.rejected>0}/><Stat l="Rows kept" v={`${ds.quality.keptPercent}%`}/></div>
  <div className="panel mt-4 p-5 text-sm text-muted">Rules applied at load: an order needs an order ID, a customer ID and a status; repeated order IDs are counted once. Tables loaded: {[['orders',ds.summary.orders],['items',ds.summary.items],['payments',ds.summary.payments],['reviews',ds.summary.reviews],['customers',ds.summary.customers],['sellers',ds.summary.sellers],['products',ds.summary.products]].map(([k,v])=>`${v.toLocaleString('en-IN')} ${k}`).join(' · ')}. Coverage {new Date(ds.summary.from).toLocaleDateString()} to {new Date(ds.summary.to).toLocaleDateString()}.</div>
  <div className="panel mt-4 overflow-auto"><table className="w-full text-sm"><thead><Th c={['Rejected row','Reason']}/></thead><tbody>{rej.length?rej.map((x,i)=><tr key={i} className="border-b border-white/5"><td className="p-3 mono">{x.id}</td><td>{x.why}</td></tr>):<tr><td className="p-4 text-muted" colSpan={2}>No rows were rejected: every order passed validation.</td></tr>}</tbody></table></div></div>}
 {tab==='sc'&&<div className="grid lg:grid-cols-[.9fr_1.1fr] gap-5 mt-5"><section className="panel p-5"><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search seller ID, city or state" className="input-dark flex-1 p-2.5"/><select value={st} onChange={e=>setSt(e.target.value)} className="input-dark p-2.5">{states.map(x=><option key={x}>{x}</option>)}</select></div>
  <div className="mt-3 max-h-[470px] overflow-auto">{list.slice(0,60).map(z=><button key={z.id} onClick={()=>{setSelectedMerchantId(z.id);setEv(null)}} className={`w-full text-left p-3 border mb-1 flex justify-between ${z.id===m.id?'border-gold/60':'border-white/10 hover:border-gold/40'}`}><span className="text-sm mono">{z.id.slice(0,10)}<span className="text-muted text-xs ml-2 font-sans">{z.city}, {z.state}</span></span><span className="mono text-gold">{z.score}</span></button>)}</div>
  <div className="flex justify-between items-center mt-3 text-xs mono text-muted"><span>{list.length.toLocaleString('en-IN')} sellers</span><button className="btn-quiet px-3 py-1 flex gap-2 items-center" onClick={()=>dl('sellers.csv','seller_id,city,state,orders,revenue_brl,cancel_rate,late_rate,review_avg,score,cancelled_order_ids,late_order_ids,low_review_order_ids\n'+list.map(x=>[x.id,x.city,x.state,x.orders,x.revenue,x.cancelRate,x.lateRate,x.reviewAvg,x.score,(x.evidence?.cancelled||[]).join(' '),(x.evidence?.late||[]).join(' '),(x.evidence?.lowReview||[]).join(' ')].join(',')).join('\n'),'text/csv')}><Download size={12}/> CSV</button></div></section>
  <section className="panel p-6"><div className="eyebrow">Seller · {m.city}, {m.state}</div><h2 className="serif text-3xl mt-1 mono break-all">{m.id.slice(0,12)}</h2><div className="flex items-end gap-4 mt-2"><div className="serif text-6xl text-gold">{m.score}<span className="text-xl text-muted">/100</span></div><div className="serif text-4xl text-gold">{carat(m.score)}</div></div>
  <p className="text-[11px] text-muted mt-1">Score = 100 minus the weighted percentile penalties below, computed against all {all.length.toLocaleString('en-IN')} sellers.</p>
  {r.factors.map(f=><div key={f.key} className="mt-4"><div className="flex justify-between text-sm"><span>{f.label} <span className="text-muted text-xs">· weight {f.w*100}%</span></span><span className="mono text-fraud">{f.points}</span></div><div className="h-1 bg-white/10 mt-2"><div className="h-full bg-gold transition-all duration-300" style={{width:`${f.pct}%`}}/></div><div className="text-[11px] text-muted mt-1">{f.value}</div><button className="mono text-[10px] text-steel mt-1" onClick={()=>setEv(ev===f.key?null:f.key)}>{ev===f.key?'hide':'show'} source order IDs ({f.ev.length})</button>{ev===f.key&&<div className="mono text-[10px] text-muted mt-1 max-h-24 overflow-auto break-all">{f.ev.length?f.ev.join(', '):'Order-level IDs for this factor are not in the prepared file. Run npm run prepare:data to attach them.'}</div>}</div>)}
  <div className="flex gap-3 mt-6 flex-wrap"><button className="btn-quiet px-3 py-2" onClick={()=>dl(`${m.id.slice(0,8)}_score.json`,JSON.stringify({seller:m.id,score:m.score,factors:r.factors.map(f=>({factor:f.label,points:f.points,percentile:f.pct,source_order_ids:f.ev}))},null,1),'application/json')}>Export JSON</button><button className="btn-quiet px-3 py-2 flex gap-2 items-center" onClick={()=>say(speech(m,r))}><Volume2 size={14}/> Listen</button></div></section></div>}
 {tab==='nw'&&<div className="mt-5 space-y-4"><div className="panel p-5 text-sm text-muted"><ShieldAlert size={14} className="inline mr-2 text-fraud"/>The network sample holds {edges.length} seller-customer links for the {new Set(edges.map(e=>e.seller)).size} highest-anomaly sellers. <span className="text-bone">{cl.length}</span> customer(s) connect more than one of them. Olist has no account-to-account transfers, so mule accounts cannot be detected. These are anomaly indicators, not confirmed fraud.</div>
  {cl.map(c=><div key={c.customer} className="panel p-5"><div className="eyebrow">Shared customer</div><div className="mono text-gold mt-2 break-all">{c.customer}</div><p className="text-sm text-muted mt-2">Bought from {c.sellers.length} flagged sellers: {c.sellers.map(s=>s.slice(0,8)).join(', ')}</p><div className="mono text-[10px] text-muted mt-2 break-all">Order IDs: {c.orders.join(', ')}</div></div>)}
  <div className="panel overflow-auto"><table className="w-full text-sm"><thead><Th c={['Seller','Anomaly','Why flagged']}/></thead><tbody>{getFraudSignals().slice(0,12).map(s=><tr key={s.id} className="border-b border-white/5"><td className="p-3 mono">{s.id.slice(0,10)}</td><td className="mono text-gold">{s.anomalyScore}</td><td className="text-xs text-muted">{s.reasons.join(' · ')}</td></tr>)}</tbody></table></div></div>}
 {tab==='fa'&&fa&&<div className="mt-5 space-y-4">{fa.out.map(g=><div key={g.label} className="panel p-6"><div className="eyebrow">{g.label}</div><div className="grid md:grid-cols-4 gap-4 mt-3"><div><div className="text-muted text-xs">Group A avg ({g.raw.na.toLocaleString('en-IN')})</div><div className="mono text-2xl">{g.raw.ma.toFixed(1)}</div></div><div><div className="text-muted text-xs">Group B avg ({g.raw.nb.toLocaleString('en-IN')})</div><div className="mono text-2xl">{g.raw.mb.toFixed(1)}</div></div><div><div className="text-muted text-xs">Gap ± 2 std. errors</div><div className={`mono text-2xl ${g.raw.sig?'text-fraud':''}`}>{g.raw.gap.toFixed(2)} ± {(2*g.raw.se).toFixed(2)}</div></div><div><div className="text-muted text-xs">Gap within same volume band</div><div className="mono text-2xl">{g.adj==null?'n/a':g.adj.toFixed(2)}</div></div></div><p className="serif text-xl mt-4">{g.verdict}</p><p className="text-[11px] text-muted mt-2">Biggest factor differences: {g.drivers.slice(0,2).map(([l,v])=>`${l} (${v>0?'+':''}${v.toFixed(1)} pts)`).join(' · ')}. Volume split at the median of {fa.medOrd} orders.</p></div>)}<p className="text-[11px] text-muted">Olist has no village/urban field. Location groups use real seller geography; the significance test compares the gap with its standard error.</p></div>}
 {tab==='st'&&<div className="mt-5 space-y-4"><div className="panel p-6"><div className="eyebrow">Stress test · {m.id.slice(0,8)} · re-scored on real distributions</div><div className="grid md:grid-cols-3 gap-7 mt-5">{[['demand','Demand shock %',100],['downtime','Downtime days (of 30)',30],['sales','Sales drop %',90]].map(([k,l,max])=><label key={k} className="text-sm">{l}<span className="mono float-right text-muted">{sl[k]}</span><input type="range" min="0" max={max} value={sl[k]} onChange={e=>setSl({...sl,[k]:+e.target.value})} className="w-full accent-[#D9A441] mt-4"/></label>)}</div><p className="serif text-3xl mt-6">Score <span className="text-gold">{m.score}</span> → <span className="text-gold">{sr.score}</span> · revenue {R(m.revenue)} → {R(sr.revenue)}</p><p className="text-[11px] text-muted mt-2">Downtime turns that share of a 30-day month into cancelled and late orders; lost sales raise the largest customer's share. All metrics come from this seller's real orders.</p></div>
  <div className="panel p-5"><div className="eyebrow">Actions that raise the score</div>{ac.length?ac.map(a=><div key={a.text} className="flex justify-between py-2 border-b border-white/5 text-sm"><span>{a.text} ({a.target})</span><span className="mono text-gold">+{a.delta} points</span></div>):<p className="text-sm text-muted mt-2">No single-metric change to the peer median raises this seller's score.</p>}</div>
  <div className="grid md:grid-cols-3 gap-4"><Stat l="Cancelled-order value" v={R(lk.cancelled)} bad/><Stat l="Revenue on late deliveries" v={R(lk.late)} bad/><Stat l="Freight paid" v={R(lk.freight)}/></div><p className="text-[11px] text-muted">Derived as revenue × observed rate. Olist has no payment-failure or refund events, so those are not shown.</p></div>}
 {tab==='pf'&&pf&&<div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="panel p-6"><div className="eyebrow">Score certificate</div><h2 className="serif text-3xl mt-1 mono break-all">{m.id.slice(0,12)}</h2><div className="serif text-5xl text-gold mt-2">{m.score}/100</div><div className="bg-white p-3 inline-block mt-4"><QRCodeSVG value={`${location.origin}/verify/${encodeURIComponent(m.id)}-${m.score}`} size={120}/></div><div className="mono text-[10px] text-muted mt-3 break-all">SHA-256 {pf.hash}</div></section>
  <section className="panel p-6"><div className="eyebrow">Lender verification</div><p className="text-sm text-muted mt-2">The lender receives a proof summary only. The hash is recomputed from the loaded dataset and compared.</p><input value={vh} onChange={e=>setVh(e.target.value)} className="input-dark w-full p-2.5 mt-3 mono text-xs"/><div className="flex gap-3 mt-3"><button className="btn-gold px-4 py-2 flex gap-2 items-center" onClick={async()=>{const n=await proof(m,r,ds);setVr(n.hash===vh.trim()?'ok':'bad')}}><Check size={14}/> Verify</button><button className="btn-quiet px-4 py-2" onClick={async()=>{const t=JSON.parse(pf.pl);t.score+=1;setVr((await sha(JSON.stringify(t)))===pf.hash?'ok':'tamper')}}>Tamper test</button></div>{vr&&<div className={`mt-4 text-sm ${vr==='ok'?'text-gold':'text-fraud'}`}>{vr==='ok'?<><ShieldCheck size={14} className="inline mr-2"/>Verified: hash matches the source data</>:vr==='tamper'?'Tampered payload rejected: hash mismatch':'Invalid: hash does not match'}</div>}<p className="text-[11px] text-muted mt-6">Olist has no loan outcomes, so no lender offers are generated.</p></section></div>}
 {tab==='as'&&<section className="panel p-6 mt-5 max-w-3xl"><div className="eyebrow">Parakh assistant · answers only from loaded data</div><div className="bg-[#0e0d0c] border border-white/10 p-4 h-[260px] overflow-auto mono text-[11px] leading-5 text-muted mt-4">{chat.length?chat.map((c,i)=><div key={i} className={c[0]==='Parakh'?'text-bone whitespace-pre-line mb-2':'text-gold'}>{c[0]}: {c[1]}</div>):'Try: "why is this score low?", "show fairness", "what is the revenue leak?", "top sellers"'}</div><div className="flex gap-3 mt-3"><input value={ci} onChange={e=>setCi(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Ask about the selected seller or the dataset" className="input-dark flex-1 p-2.5"/><button className="btn-gold px-4 py-2" onClick={submit}>Ask</button><button className="btn-quiet px-3" onClick={()=>chat.length&&say(chat.at(-1)[1])}><Volume2 size={15}/></button></div></section>}
 </div>}
