import {useEffect,useMemo,useRef,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight,Check,Clock3,GripVertical,LoaderCircle,Pencil,Play,RefreshCw,RotateCcw,TerminalSquare,Trash2,Database,AlertTriangle} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {buildAnalysis,workflowSteps} from '../lib/queryEngine';

const STEP_TIMES=[1500,1700,1900,1800,1600,1500];
export default function Workflows(){
 const loc=useLocation(),nav=useNavigate();const {addRun,setActivity,dataset}=useApp();
 const [prompt,setPrompt]=useState(loc.state?.prompt||'');const [controls,setControls]=useState(loc.state?.controls||{state:'All',category:'All',minValue:'',maxValue:''});
 const [steps,setSteps]=useState(()=>workflowSteps(loc.state?.prompt||'Analyse the loaded data',loc.state?.controls||{}));const [running,setRunning]=useState(false),[statuses,setStatuses]=useState([]),[logs,setLogs]=useState([]),[done,setDone]=useState(false),[activeProgress,setActiveProgress]=useState(0),[startedAt,setStartedAt]=useState(null),[elapsed,setElapsed]=useState(0),[analysis,setAnalysis]=useState(null);const timers=useRef([]);
 useEffect(()=>()=>timers.current.forEach(x=>typeof x==='number'?clearTimeout(x):clearInterval(x)),[]);
 useEffect(()=>{if(!running||!startedAt)return;const id=setInterval(()=>setElapsed(Date.now()-startedAt),200);return()=>clearInterval(id)},[running,startedAt]);
 const addLog=m=>setLogs(l=>[...l,`${new Date().toLocaleTimeString()}  ${m}`]);
 const build=()=>{const next=workflowSteps(prompt||'Analyse the loaded data',controls);setSteps(next);setStatuses([]);setLogs([]);setDone(false);setAnalysis(null);setActiveProgress(0)};
 const approve=()=>{if(running||!steps.length)return;timers.current.forEach(x=>typeof x==='number'?clearTimeout(x):clearInterval(x));timers.current=[];const result=buildAnalysis(prompt||'Analyse the loaded data',controls);setAnalysis(result);setRunning(true);setDone(false);setActiveProgress(0);setElapsed(0);setStartedAt(Date.now());setStatuses(steps.map(()=> 'Waiting'));setLogs([]);setActivity({speed:.9});addLog(`WORKFLOW START · ${prompt||'Analyse the loaded data'}`);addLog(`SOURCE · ${dataset?.summary?.orders?.toLocaleString('en-IN')||'—'} orders · ${dataset?.summary?.sellers?.toLocaleString('en-IN')||'—'} sellers · ${dataset?.summary?.products?.toLocaleString('en-IN')||'—'} products`);if(result.filters.length)addLog(`FILTERS · ${result.filters.join(' · ')}`);
 let i=0;const runStep=()=>{if(i>=steps.length){setRunning(false);setDone(true);setActiveProgress(100);setActivity({speed:.16});addLog(`✓ WORKFLOW COMPLETE · ${result.total.toLocaleString('en-IN')} matching records · ${result.title}`);addRun({id:Date.now(),prompt,time:new Date().toLocaleString(),status:'Done',count:`${result.total.toLocaleString('en-IN')} matching ${result.entity}`});return}const idx=i,step=steps[idx];setStatuses(s=>s.map((v,j)=>j===idx?'Running':j<idx?'Done':v));setActiveProgress(7);addLog(`→ ${step}`);const lines=idx===0?[`Request interpreted as ${result.entity}.`,`Metric selected: ${result.metric}.`]:idx===1?[result.filters.length?`Applied ${result.filters.length} user/data filters.`:'No extra filter supplied; using the full loaded dataset.']:idx===2?[`Calculated ${result.metric} directly from source-derived fields.`]:idx===3?[result.metric==='anomalyScore'?'Compared network/operational signals by relative dataset percentile.':'Compared requested values across the loaded records.']:idx===4?[`Attached source IDs and observable fields to the result set.`]:[`Prepared ${result.total.toLocaleString('en-IN')} matching records for review.`];lines.forEach((line,k)=>timers.current.push(setTimeout(()=>addLog(`  ${line}`),320+k*380)));const total=STEP_TIMES[idx%STEP_TIMES.length],started=Date.now();const pid=setInterval(()=>setActiveProgress(Math.min(96,7+Math.round((Date.now()-started)/total*89))),100);timers.current.push(pid);timers.current.push(setTimeout(()=>{clearInterval(pid);setStatuses(s=>s.map((v,j)=>j===idx?'Done':v));setActiveProgress(100);addLog(`✓ ${step} · done`);i++;timers.current.push(setTimeout(()=>{setActiveProgress(0);runStep()},260))},total))};timers.current.push(setTimeout(runStep,250));};
 const edit=i=>{const n=window.prompt('Rename step',steps[i]);if(n?.trim())setSteps(s=>s.map((x,j)=>j===i?n.trim():x))};const remove=i=>setSteps(s=>s.filter((_,j)=>j!==i));const move=(i,d)=>setSteps(s=>{const a=[...s],j=i+d;if(j<0||j>=a.length)return a;[a[i],a[j]]=[a[j],a[i]];return a});
 const doneCount=statuses.filter(x=>x==='Done').length;const progress=steps.length?Math.round(((doneCount+(running&&doneCount<steps.length?activeProgress/100:0))/steps.length)*100):0;const elapsedText=useMemo(()=>`${Math.floor(elapsed/60000)}:${String(Math.floor((elapsed%60000)/1000)).padStart(2,'0')}`,[elapsed]);const icon=s=>s==='Done'?<Check size={13}/>:s==='Running'?<LoaderCircle size={13} className="animate-spin"/>:<Clock3 size={13}/>;
 return <div className="max-w-6xl"><div className="eyebrow">Describe it, we build the workflow</div><h1 className="serif text-5xl mt-2">Workflow desk</h1><p className="text-muted mt-2 max-w-3xl">Any question is accepted. Parakh interprets the request, selects source records, calculates the relevant metric and prepares evidence from your CSV dataset.</p>
 <div className="panel mt-7 p-5"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Try anything: product revenue, sellers in a state, late delivery, unusual customer concentration, price, category..." className="bg-transparent outline-none w-full min-h-[100px] resize-none serif text-2xl placeholder:text-muted/50"/><div className="flex flex-wrap justify-between gap-3 mt-3"><div className="text-[11px] mono text-muted flex items-center gap-2"><Database size={13}/> {dataset?.summary?.orders?.toLocaleString('en-IN')||'—'} orders · {dataset?.summary?.sellers?.toLocaleString('en-IN')||'—'} sellers · {dataset?.summary?.products?.toLocaleString('en-IN')||'—'} products</div><div className="flex gap-3"><button className="btn-quiet px-4 py-2" onClick={()=>nav('/')}>Change prompt</button><button onClick={build} disabled={!prompt.trim()&&!Object.values(controls).some(v=>v&&v!=='All')} className="btn-quiet px-4 py-2 flex gap-2 items-center"><RefreshCw size={14}/> Build plan</button></div></div></div>
 <div className="grid lg:grid-cols-[1.05fr_.95fr] gap-5 mt-5"><section className="panel p-6"><div className="flex justify-between items-start"><div><div className="eyebrow">Plan preview</div><h2 className="serif text-3xl mt-1">{steps.length} steps</h2></div><div className="mono text-xs text-muted">{running?`${progress}% running`:done?'100% complete':'ready'}</div></div><div className="mt-5">{steps.map((s,i)=><div key={`${s}-${i}`} className="flex items-center gap-2 border-b border-white/10 py-3"><button onClick={()=>move(i,-1)} disabled={running} title="Move up"><GripVertical size={15} className="text-muted"/></button><span className="mono text-xs text-gold w-6">{String(i+1).padStart(2,'0')}</span><span className="flex-1 text-sm">{s}</span><button onClick={()=>edit(i)} disabled={running}><Pencil size={14}/></button><button onClick={()=>remove(i)} disabled={running}><Trash2 size={14} className="text-muted"/></button></div>)}</div><button onClick={approve} disabled={running||!steps.length} className="btn-gold px-5 py-3 mt-6 flex items-center gap-2">{running?<><LoaderCircle size={16} className="animate-spin"/> Running {progress}%</>:done?<><RotateCcw size={16}/> Run again</>:<><Play size={15}/> Approve & run</>}<ArrowRight size={16}/></button><p className="text-[11px] text-muted mt-3">The plan is generated from your wording and optional filters. You can edit it before execution.</p></section>
 <section className="panel p-6"><div className="flex justify-between items-start"><div><div className="eyebrow">Task monitor</div><h2 className="serif text-3xl mt-1">{running?'Analysis in motion':done?'Evidence ready':'Ready to run'}</h2></div><div className="mono text-xs text-muted">{elapsedText}</div></div><div className="space-y-2 mt-5">{steps.map((s,i)=>{const st=statuses[i]||'Waiting';return <div className={`flex items-center gap-3 text-sm py-2 px-2 border-l ${st==='Running'?'border-steel bg-white/[0.03]':st==='Done'?'border-gold/50':'border-white/5'}`} key={`${s}-${i}`}><span className={`w-5 h-5 rounded-full border border-white/10 flex items-center justify-center ${st==='Done'?'text-gold':st==='Running'?'text-steel':'text-muted/50'}`}>{icon(st)}</span><span className="flex-1">{s}</span><span className={`mono text-[10px] ${st==='Running'?'text-steel':st==='Done'?'text-gold':'text-muted'}`}>{st}</span></div>})}</div><div className="mt-5"><div className="flex justify-between text-[10px] mono text-muted mb-2"><span>WORKFLOW PROGRESS</span><span>{progress}%</span></div><div className="h-1 bg-white/10 relative overflow-hidden"><div className="absolute left-0 top-0 h-full bg-gold transition-all duration-300" style={{width:`${progress}%`}}/></div></div><div className="mt-6"><div className="flex justify-between items-center mb-2"><div className="eyebrow">Live log</div>{running&&<span className="mono text-[9px] text-fraud animate-pulse">● LIVE</span>}</div><div className="bg-[#0e0d0c] border border-white/10 p-4 h-[225px] overflow-auto mono text-[11px] leading-5 text-muted">{logs.length?logs.map((l,i)=><div key={i} className={l.includes('✓')?'text-gold':l.includes('→')?'text-bone':''}>{l}</div>):<div className="text-muted/50">Approve & run to stream real execution stages here…</div>}{running&&<div className="text-steel animate-pulse mt-1">▌</div>}</div></div>{done&&<div className="mt-4 flex gap-3"><button onClick={()=>nav('/merchants')} className="btn-gold px-4 py-2 flex gap-2 items-center"><Check size={15}/> Open seller results</button><button onClick={()=>nav('/products')} className="btn-quiet px-4 py-2">Open products</button></div>}</section></div>
 {done&&analysis&&<section className="panel mt-5 p-6"><div className="flex justify-between items-start"><div><div className="eyebrow">Computed result</div><h2 className="serif text-3xl mt-1">{analysis.title}</h2><p className="text-sm text-muted mt-1">{analysis.reason}</p></div><div className="mono text-sm"><AlertTriangle size={14} className="inline mr-2 text-fraud"/>{analysis.total.toLocaleString('en-IN')} matches</div></div><div className="mt-5 overflow-auto"><table className="w-full text-sm"><thead className="text-muted text-xs"><tr className="border-b border-white/10">{(analysis.entity==='products'?['Product','Category','Revenue','Avg price','Orders']:['Seller','State','Revenue','Orders','Score','Anomaly']).map(x=><th className="text-left p-3 font-normal" key={x}>{x}</th>)}</tr></thead><tbody>{analysis.rows.slice(0,12).map(r=><tr key={r.id} className="border-b border-white/5"><td className="p-3">{r.name||r.id}</td><td>{r.category||r.state}</td><td className="mono">R$ {Number(r.revenue||0).toLocaleString('en-IN',{maximumFractionDigits:0})}</td><td className="mono">{analysis.entity==='products'?r.avgPrice?.toLocaleString('en-IN',{maximumFractionDigits:2}):r.orders?.toLocaleString('en-IN')}</td>{analysis.entity==='products'?<td className="mono">{r.orders?.toLocaleString('en-IN')}</td>:<><td className="mono">{r.score}/100</td><td className="mono">{r.anomalyScore||r.networkAnomaly||0}</td></>}</tr>)}</tbody></table></div></section>}
 </div>
}
