// AiRecommendationsCard.tsx
import React from 'react';
import { Sparkles, ArrowUpRight, CheckCircle2, AlertCircle, Clock } from 'lucide-react';
import { Link } from 'react-router-dom';

interface Recommendation {
  id: string;
  title: string;
  category: 'Energy' | 'Process' | 'Solar' | 'HVAC';
  co2Reduction: string;
  costSaving: string;
  roi: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  applied?: boolean;
}

const defaultRecommendations: Recommendation[] = [
  {
    id: 'rec-1',
    title: 'Install Variable Frequency Drives (VFD) on Line 2 Water Chillers',
    category: 'HVAC',
    co2Reduction: '-48.5 tCO2e/yr',
    costSaving: '$14,200/yr',
    roi: '1.4 years',
    priority: 'HIGH'
  },
  {
    id: 'rec-2',
    title: 'Deploy 250 kW Rooftop Solar PV at Okhla Assembly Plant',
    category: 'Solar',
    co2Reduction: '-185.0 tCO2e/yr',
    costSaving: '$36,800/yr',
    roi: '2.8 years',
    priority: 'HIGH'
  },
  {
    id: 'rec-3',
    title: 'Shift Electro-Plating Batch Processes to Night Off-Peak Hours',
    category: 'Process',
    co2Reduction: '-22.0 tCO2e/yr',
    costSaving: '$9,400/yr',
    roi: 'Immediate',
    priority: 'MEDIUM'
  }
];

export const AiRecommendationsCard: React.FC = () => {
  return (
    <div className="rounded-2xl bg-[#081512]/90 border border-emerald-950/60 p-5 backdrop-blur-xl">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white">AI Decarbonization Recommendations</h3>
            <p className="text-xs text-emerald-400/60">Autonomous prescriptive actions generated by GreenMetriX Copilot</p>
          </div>
        </div>
        <Link
          to="/action-planner"
          className="text-xs font-semibold text-emerald-400 hover:text-emerald-300 flex items-center gap-1 transition-colors"
        >
          View Roadmap <ArrowUpRight className="w-3.5 h-3.5" />
        </Link>
      </div>

      <div className="space-y-3">
        {defaultRecommendations.map((rec) => (
          <div
            key={rec.id}
            className="p-3.5 rounded-xl bg-[#040d0c]/70 border border-emerald-950/80 hover:border-emerald-700/60 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3 group"
          >
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span
                  className={`text-[10px] font-bold px-2 py-0.5 rounded border ${
                    rec.priority === 'HIGH'
                      ? 'bg-rose-500/10 text-rose-400 border-rose-500/30'
                      : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
                  }`}
                >
                  {rec.priority}
                </span>
                <span className="text-[10px] uppercase tracking-wider text-emerald-400/60">{rec.category}</span>
              </div>
              <h4 className="text-xs font-semibold text-white group-hover:text-emerald-300 transition-colors">
                {rec.title}
              </h4>
              <div className="flex items-center gap-4 text-[11px] text-emerald-400/70 pt-1">
                <span>CO₂ Impact: <strong className="text-emerald-300 font-mono">{rec.co2Reduction}</strong></span>
                <span>Savings: <strong className="text-amber-300 font-mono">{rec.costSaving}</strong></span>
                <span>ROI: <strong className="text-cyan-300 font-mono">{rec.roi}</strong></span>
              </div>
            </div>

            <div className="flex items-center gap-2 self-end sm:self-center">
              <Link
                to="/digital-twin"
                className="text-xs font-medium px-3 py-1.5 rounded-lg bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 transition-all"
              >
                Simulate
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
