ALTER TABLE analysis
ADD COLUMN IF NOT EXISTS overall_insights JSONB,
ADD COLUMN IF NOT EXISTS top_problems JSONB,
ADD COLUMN IF NOT EXISTS user_segments JSONB,
ADD COLUMN IF NOT EXISTS roadmap JSONB;
